### ISSUE TITLE
Hacktoberfest First Commit

### ISSUE THREAD

**Issue by Sanchitbajaj02** [RCC-MRU/todo-app-frontend#22]
Contribute here for hacktoberfest

**Comment by CrackerSuman** [comment]
@amarjeetsinha,  Can you assign this issue to me for hacktoberfest ?

**Comment by Sanchitbajaj02** [comment]
@aishwarya-g-thoughtworks my team had created this project as an objective of learning Reactjs. So I listed this repo in Hacktoberfest in the hope of getting new features added to this project or correcting our mistakes by fellow developers.

You can enhance or include any feature you want that you are suitable with while maintaining its integrity.
Thanks.
